### ISSUE TITLE
Add a command to try

### ISSUE THREAD

**Issue by MoOx** [deprint/break-time#2]
A command (in the command palette) to try the plugin when you get it would be nice.

**Comment by fstiewitz** [comment]
Now that I think about it, yes.
You could open the dev tools (View -> Developer -> Toggle developer tools) and enter `atom.packages.getActivePackage('break-time').mainModule.break()` but a command in the command palette would be easier.
Edit: and `atom.packages.getActivePackage('break-time').mainModule.unbreak()` to stop the break.

**Comment by fstiewitz** [comment]
Fixed in `v0.2.0` (`break-time:break`)

**Comment by MoOx** [comment]
👌🏼
