### ISSUE TITLE
Progress bar looks weird

### ISSUE THREAD

**Issue by chenglou** [deprint/break-time#4]
![screenshot 2016-02-07 02 21 10](https://cloud.githubusercontent.com/assets/1909539/12871286/771ecffe-cd41-11e5-8720-2187497e6976.png)

I'm guessing this is a small bug?

**Comment by fstiewitz** [comment]
Looks like a styling problem. What theme do you use ?

**Comment by chenglou** [comment]
Oh right! Atom Dark.

**Comment by chenglou** [comment]
Thanks! That worked =).
